volumes:
  pocketid_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.8.223,nolock,soft,rw"
      device: ":/mnt/tank-ephemeral/app_clone/app_configs/pocketID"

services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2
    restart: unless-stopped
    env_file: .env
    ports:
      - 1411:1411
    volumes:
      - "pocketid_data:/app/data"
    # Optional healthcheck
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
